# Generated by Django 5.1.6 on 2025-03-07 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['views', 'free_views_remaining'], name='marketplace_views_e9ac30_idx'),
        ),
    ]
